### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by gubesch** [gubesch/go-quiz#1]
Docker integration with ready to deploy database see https://github.com/gubesch/go-quiz/tree/master/migration

**Comment by jamillosantos** [comment]
I am not sure what should I do here? Could you explain it better?

**Comment by gubesch** [comment]
Hi, in this repo you can find a simple go api.
And it uses a MySQL DB connection which is defined in the link file... 

I need  a docker container which provides a db and includes my go application so when i launch the fibtainer i am ready to go with the api

**Comment by jamillosantos** [comment]
Alright! Assign it to be please. I will be creating a `docker-compose.yaml` will both your application and the MySQL. And also a "production-ready" image too.

**Comment by gubesch** [comment]
done ;)

**Comment by jamillosantos** [comment]
Last question @gubesch: Do you want this image for development or is it a production-ready image?

**Comment by jamillosantos** [comment]
I just realized you are not using go modules. I will be enabling it. It will make your life easier alright? I just finished the development image. I will be doing the PR. If you need anything else I can update it later on.
